### ISSUE TITLE
can it work with react native?

### ISSUE THREAD

**Issue by fukemy** [akhil-rana/virtual-bg#5]
as title

**Comment by akhil-rana** [comment]
I have not tested it with React Native.

I'm not sure if anyone else has or not. 

But if it works with react as well as chromium on mobile then it might just work in react native too..

Though users have reported that safari has some issues so I'm not confident for ios. 

I'm not much familiar with ReactNative so if you try it out let us know. :)

**Comment by fukemy** [comment]
bro thanks you for very quick reply. I know it's silly question, but im not familiar with web dev, can i ask you a question? 

I saw your guide :
```
// applies an image background
const image = new Image();
image.src = 'https://imageurl.jpg'
applyImageBackground(image);

```

Did you mean you have a image above webrtcView, then apply effect into this image?

**Comment by akhil-rana** [comment]
> bro thanks you for very quick reply. I know it's silly question, but im not familiar with web dev, can i ask you a question?
> 
> I saw your guide :
> 
> ```
> // applies an image background
> const image = new Image();
> image.src = 'https://imageurl.jpg'
> applyImageBackground(image);
> ```
> 
> Did you mean you have a image above webrtcView, then apply effect into this image?

I'm not sure I understand your question. I'll try to explain ..


This adds a virtual image as a background to your camera feed.

`const image = new Image();`
`image.src = 'https://imageurl.jpg'`

These 2 lines creates a new JS Image() Object dynamically and adds it to the canvas which then acts as your virtual background.

You can see the working in the [demo URL](http://demo.virtualbg.akhilrana.com/). 
The code of the demo is also open for you to view (top right icon on demo page)

**Comment by fukemy** [comment]
yes, thanks u i know it now
